name: PlayerHeadShop
version: '2.0.0-beta-2'
main: com.twjo.playerheadshop.PlayerHeadShop
api-version: '1.21'
folia-supported: true
softdepend:
  - Vault
description: A lightweight Paper/Folia Minecraft plugin to purchase player heads with custom items, Vault economy, and GUI.
author: TW_Jo

permissions:
  playerheadshop.use:
    description: 允許玩家使用 /buyhead 購買自己的頭顱
    default: true
  playerheadshop.admin:
    description: 允許管理員重新加載 PlayerHeadShop 設定檔與查詢交易記錄
    default: op
